services:
  config-server:
    build: ./config-server
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s

  eureka-server:
    build: ./eureka-server
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    depends_on:
      config-server:
        condition: service_healthy
    ports:
      - 8761:8761

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bp4JSd7T3D5LzQmV
      POSTGRES_DB: guess_game_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres_db" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 5430:5432

  game-service:
    build: ./service
    depends_on:
      eureka-server:
        condition: service_healthy
      postgres:
        condition: service_healthy

  telegram-service:
    build: ./service
    depends_on:
      eureka-server:
        condition: service_healthy

  gpt-service:
    build: ./gpt-service
    depends_on:
      eureka-server:
        condition: service_healthy